import os
from dotenv import load_dotenv


load_dotenv()

EVOLUTION_API_URL = os.getenv("EVOLUTION_API_URL")
EVOLUTION_INSTANCE_NAME = os.getenv("EVOLUTION_INSTANCE_NAME")
EVOLUTION_AUTHENTICATION_API_KEY = os.getenv("AUTHENTICATION_API_KEY")

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL_NAME = os.getenv('OPENAI_MODEL_NAME')
OPENAI_MODEL_TEMPERATURE = os.getenv('OPENAI_MODEL_TEMPERATURE')

GROQ_MODEL_NAME = os.getenv('GROQ_MODEL_NAME')
GROQ_MODEL_TEMPERATURE = os.getenv('GROQ_MODEL_TEMPERATURE')


VECTOR_STORE_PATH = os.getenv('VECTOR_STORE_PATH')
RAG_FILES_DIR = os.getenv('RAG_FILES_DIR')


AI_CONTEXTUALIZE_PROMPT = os.getenv('AI_CONTEXTUALIZE_PROMPT')
AI_SYSTEM_PROMPT = os.getenv('AI_SYSTEM_PROMPT')


REDIS_URL = os.getenv('CACHE_REDIS_URI')
BUFFER_KEY_SUFIX = os.getenv('BUFFER_KEY_SUFIX')
DEBOUNCE_SECONDS = os.getenv('DEBOUNCE_SECONDS')
BUFFER_TTL = os.getenv('BUFFER_TTL')



DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_HOST = os.getenv("DB_HOST")
STRING_CONEXAO = f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

