# Mapeamento de abreviações para nomes fantasia exatos do banco de dados.
# Chave   = abreviação (como o usuário pode digitar)
# Valor   = nome fantasia exato gravado na coluna `Fantasia` do banco
#
# Para adicionar ou ajustar um de/para, edite apenas este arquivo.

ABREVIACAO_TO_FANTASIA: dict[str, str] = {
    "BPBARRA":              "BOA PRACA BARRA",
    "BPBSB":                "BOA PRACA BRASILIA",
    "BPCWB":                "BOA PRACA CURITIBA",
    "BPI":                  "BOA PRACA ITAIM",
    "BPIPA":                "BOA PRACA IPANEMA",
    "BPL":                  "BOA PRACA RJ",
    "BPM":                  "BOA PRACA MORUMBI",
    "BPP":                  "BOA PRACA PAULISTA",
    "COZINHA CENTRAL NINO": "COZINHA CENTRAL NINO",
    "DA MARINO IPANEMA":    "DA MARINO IPA",
    "DA MARINO ITAIM":      "DA MARINO",
    "DA MARINO MORUMBI":    "DA MARINO SHOPPING MORUMBI",
    "ETEP":                 "EU TU ELES PAULISTA",
    "FORNO":                "FORNO DA PINO",
    "GIULIETTA ITAIM":      "GIULIETTA MATRIZ",
    "NINETTO BARRA":        "NINETTO RIO DESIGN",
    "NINETTO BH":           "NINETTO BH",
    "NINETTO CAMPINAS":     "NINETTO DOM PEDRO",
    "NINETTO CURITIBA":     "NINETTO BARIGUI",
    "NINETTO ELDORADO":     "NINETTO ELDORADO",
    "NINETTO FORTALEZA":    "NINETTO FORTALEZA",
    "NINETTO MORUMBI":      "NINETTO NONNA",
    "NINETTO RECIFE":       "NINETTO RECIFE",
    "NINETTO UBERLANDIA":   "NINETTO UBERLANDIA",
    "NINO BH":              "NINO BELO HORIZONTE",
    "NINO BSB":             "NINO BRASILIA",
    "NINO CC":              "NINO CC",
    "NINO GOIANIA":         "NINO GOIANIA",
    "NINO IPANEMA":         "NINO IPA",
    "NINO ITAIM":           "NINO ITAIM BUCA",
    "PEPPINO":              "PEPPINO CANTINA",
    "PRINCESA BARRA":       "PRINCESA BARRA",
    "PRINCESA LEBLON":      "PRINCESA LEBLON",
    "RAINHA BARRA":         "GALETO RAINHA BARRA",
    "RAINHA CLODOMIRO":     "GALETO RAINHA ITAIM",
    "RAINHA LEBLON":        "RAINHA LEBLON",
    "RAINHA PAULISTA":      "RAINHA PAULISTA",
    "RAINHA PEDROSO":       "RAINHA SP",
    "REDUX BARRA":          "IRAJA REDUX BARRA",
    "REDUX LEBLON":         "IRAJA REDUX LEBLON",
    "REDUX RIO SUL":        "IRAJA REDUX RIO SUL",
    "TBBH":                 "TATU BOLA BELO HORIZONTE",
    "TBCAMP":               "TATU BOLA CAMPINAS",
    "TBCG":                 "TATU BOLA CAMPO GRANDE",
    "TBF":                  "TATU BOLA FORTALEZA",
    "TBG":                  "TATU BOLA GOIANIA",
    "TBI":                  "TATU BOLA ITAIM",
    "TBJ":                  "TATU BOLA JARDINS",
    "TBPAMP":               "TATU BOLA PAMPULHA",
    "TBREC":                "TATU BOLA RECIFE",
    "TBRP":                 "TATU BOLA RIBEIRAO PRETO",
    "TBSSA":                "TATU BOLA SALVADOR",
    "TBT":                  "TATU BOLA TATUAPE",
    "TBU":                  "TATU BOLA UBERLANDIA",
    "TBVO":                 "TATU BOLA VILA OLIMPIA",
    "TBZN":                 "TATU BOLA ZONA NORTE",
    "TTZPOMP":              "TATUZINHO POMPEIA",
}
